[theme]
base = "dark"
primaryColor = "#8C663E"            # Cambridge Leather
backgroundColor = "#090201"         # Pupil â€“ hitam kecokelatan
secondaryBackgroundColor = "#200E03" # Super Black / cokelat pekat
textColor = "#F9FAFB"
font = "sans serif"
